name: DevSecOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para que TruffleHog pueda ver el historial completo
      - name: Escanear secretos
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unverified,unknown
      - name: Construir la imagen Docker
        run: |
          echo "Construyendo la imagen..."
          cd app
          docker build -t app-demo:${{ github.sha }} .
          echo "¡Imagen construida con éxito!"